const C = 'BACKLOG'

export const GET_LIST_SPRINT = `${C}_GET_LIST_SPRINT`
export const GET_SPRINT_ACTIVE = `${C}GET_SPRINT_ACTIVE`
export const GET_SPRINT_ACTIVE_INFO = `${C}GET_SPRINT_ACTIVE_INFO`
export const CREATE_SPRINT = `${C}_CREATE_SPRINT`
export const START_SPRINT = `${C}_START_SPRINT`
export const COMPLETE_SPRINT = `${C}_COMPLETE_SPRINT`
export const GET_LIST_BACKLOG_ISSUE = `${C}_GET_LIST_BACKLOG_ISSUE`
export const RESET_DATA = `${C}_RESET_DATA`
export const CHANGE_COMPLETE_SPRINT_VALUE = `${C}_CHANGE_COMPLETE_SPRINT_VALUE`