const C = 'COMPONENT';

export const CREATE_COMPONENT = `${C}_CREATE_COMPONENT`
export const UPDATE_COMPONENT = `${C}_UPDATE_COMPONENT`
export const SELECT_COMPONENT = `${C}_SELECT_COMPONENT`
export const RESET_DATA = `${C}_RESET_DATA`
export const GET_LIST_COMPONENT = `${C}_GET_LIST_COMPONENT`
export const CHANGE_ADD_COMPONENT_FORM_VALUE = `${C}_CHANGE_ADD_COMPONENT_FORM_VALUE`
export const RESET_CREATE_COMPONENT_STATUS = `${C}_RESET_CREATE_COMPONENT_STATUS`
export const CHANGE_SEARCH_VALUE = `${C}_CHANGE_SEARCH_VALUE`