const C = 'RELEASE';

export const CREATE_VERSION = `${C}_CREATE_VERSION`
export const UPDATE_VERSION = `${C}_UPDATE_VERSION`
export const SELECT_VERSION = `${C}_SELECT_VERSION`
export const DELETE_VERSION = `${C}_DELETE_VERSION`
export const RESET_DATA = `${C}_RESET_DATA`
export const GET_LIST_VERSION = `${C}_GET_LIST_VERSION`
export const CHANGE_ADD_VERSION_FORM_VALUE = `${C}_CHANGE_ADD_VERSION_FORM_VALUE`
export const RESET_CREATE_VERSION_STATUS = `${C}_RESET_CREATE_VERSION_STATUS`
export const CHANGE_SEARCH_VALUE = `${C}_CHANGE_SEARCH_VALUE`
export const GET_VERSION_DETAIL = `${C}_GET_VERSION_DETAIL`
export const RELEASE_VERSION_STATUS = `${C}_RELEASE_VERSION_STATUS`
export const UNRELEASE_VERSION_STATUS = `${C}_UNRELEASE_VERSION_STATUS`
export const RESET_RELEASE_STATUS = `${C}_RESET_RELEASE_STATUS`