export const GET_LIST_WORKFLOW = 'GET_LIST_WORKFLOW'
export const CREATE_STEP = 'CREATE_STEP'
export const UPDATE_WORKFLOW_STATUS = 'UPDATE_WORKFLOW_STATUS'
export const SWAP_WORKFLOW = 'SWAP_WORKFLOW'